import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/share/home/Navbar";
import Footer from "@/components/share/home/Footer";


const PoppinsFont = Poppins({
  variable: "--font-Poppins",
  weight: ["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"      
      className={`${PoppinsFont.className} h-full antialiased`}
    >
      <body>
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
